spring:
  jpa:
    database: MYSQL
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect.storage_engine: innodb
  datasource:
    hikari:
      maximum-pool-size: 3

flyway:
  locations: classpath:production-plan/flyway/{vendor}
  table: flyway_schema_history_production_plan
  encoding: UTF-8
  baseline-on-migrate: true
